config/routes.rb
PersonalWebsite::Application.routes.draw do

  root  'static_pages#home'
  match '/projects',    to: 'static_pages#projects',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/manifesto',   to: 'static_pages#manifesto',   via: 'get'
  match '/challenges', to: 'static_pages#challenges', via: 'get'
  match '/achievements', to: 'static_pages#achievements', via: 'get'
  match '/impossible_list', to:  'static_pages#impossible_list', via: 'get'
  match '/what_am_I_doing_now', to: 'static_pages#what_doing_now', via: 'get'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end

  def challenges
  end

  def manifesto
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Abhishek Bose"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; 2016: Abhishek Bose
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Abhishek Bose", root_path, id: "logo", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- <ul class="nav pull-right"> -->
          <li><%= link_to "Blog", "http://blog.abhishekbose.com" %></li>
          <li><%= link_to "Bio",    about_path %></li>
          <li><%= link_to "Resume", "/resume.pdf" %></li>
          <li><%= link_to "Manifesto", manifesto_path %></li>
        <!-- </ul> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
  <%= render 'layouts/header' %>   
    <div id="wrap">
    <div id="main" class="container clear-top ">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>     
  </div>
      <%= render 'layouts/footer' %>
     
  </body>
</html>

app/views/static_pages/achievements.html.erb
<% provide(:title, 'Achievements ') %>
<article>
<h2>Achievements</h2>
	<ul>
<li>Completed a half marathon</li>
<li>Part of the Amdocs Football team and college football team</li>
<li>Won the coding competition held in Amdocs quarterly</li>
<li>Won the Instagram Photography Contest held in Amdocs</li>
<li>3rd prize in Programming contest <strong><em>Codiac</em></strong> in Kritansh-09 of KIIT-University</li>
<li>Recognition award by AMDOCS within 6 months after joining</li>
<li>Was part of the team that started Toastmasters club at Amdocs</li>
</ul>
</article>

app/views/static_pages/challenges.html.erb
<% provide(:title, 'My Challenges ') %>
<article><h2>Challenges </h2>
<ol>
<li class="finished">Write 750 words daily for a month </li>
<li class="current">Complete 10 pomodoros every day for a month </li>
<li class="current">Complete 100 pomodoros in a week </li>
<li>Publish a photograph every week </li>
</ol>
</article>

app/views/static_pages/home.html.erb
  <div class="container-fluid">
      <!-- Example row of columns -->
      <div class="row">
        <div class=" col-md-4 category">
          <%= link_to image_tag("projects.jpg", :class => "img_category"), projects_path%>
          <h2>Projects</h2>
        </div>
        <div class=" col-md-4 category">
          <%= link_to image_tag("abhishek.jpg", :class => "img_category") ,"/what_am_I_doing_now"%>
          <h2>What am I doing right now ?? </h2>
        </div>
        <div class=" col-md-4 category">
          <%= link_to image_tag("challenges.jpg", :class => "img_category"), challenges_path %>
          <h2>Challenges</h2>
        </div>
      </div>
      <div class="row">
        <div class=" col-md-4 category">
           <%=link_to image_tag("sample.jpg", :class => "img_category"), "http://www.flickr.com/photos/95955767@N07/sets/", target: "_blank" %>
          <h2>Photography</h2>
        </div>
        <div class=" col-md-4 category">
          <%= link_to image_tag("achievements.jpg", :class => "img_category"), achievements_path %>
          <h2>Achievements</h2>
        </div>

               <div class=" col-md-4 category">
          <%=link_to image_tag("bucket_list.jpg", :class => "img_category"), "/impossible_list" %>
          <h2>My Impossible List</h2>
        </div>
      </div>



  </div>

app/views/static_pages/impossible_list.html.erb
<% provide(:title, 'My Impossible List') %>
<article>
<h2>My impossible list </h2>
<div>Fitness/Health Goals</div>
<div>
<ul>
<li class="finished">Run a 5K </li>
<li class="finished">Run a half marathon</li>
<li>Run a marathon ( 42.195 km )</li>
<li>Learn to swim</li>
</ul>
<div>Professional Goals</div>
</div>
<div>
<ul>
<li class="finished">Make 20k in a month without having the restriction of time and space</li>
<li>Write a book </li>
<li>Speak to an audience of more than 500 people </li>
</ul>
<div>Skill Goals </div>
</div>
<div>
<ul>
<li class="finished">Learn to create a website ( I have 3 operational websites currently )</li>
<li>Be an expert in Ruby on Rails</li>
</ul>
<div>Fun and/or Insane goals</div>
</div>
<div>
<ul>
<li>Spend a month in a foreign country </li>
<li>Scuba diving </li>
</ul>
</div>
<div>Travel goals </div>
<div>
<ul>
<li>Visit Ireland using my own money </li>
<li class="finished">Visit Barcelona and watch Messi play</li>
<li>Visit Ladakh </li>
<li>Visit Andaman and Nicobar </li>
<li>Visit Maldives</li>
</ul>
</div>
</article>

app/views/static_pages/manifesto.html.erb
<article>
<%= image_tag("india-abhishek-bose.jpg", class:"center") %>
<p class="center">
  Credits go to <a href="http://www.maptia.com">maptia</a> for the beautiful words :)
</p>
</article>

app/views/static_pages/projects.html.erb
<% provide(:title, 'My Projects ') %>
<article>
	<h2>Projects</h2>
<h3>Professional</h3>
<p class="project"><span class="headline">Kimaya</span></p>
	<p>
	Description : A web app to provide right nutrition to new born babies during their stay at neonatal intensive care units(NICU).
</p>
<p>
Technologies: Ruby on Rails
</p>

<p class="project"><span class="headline">Canopy</span></p>
	<p>
	Description :  An account aggregation and reporting platform for high net worth individuals and their wealth managers.
</p>
<p>
Technologies: Ruby on Rails
</p>

<p class="project"><span class="headline">Ensemble</span>
</p><p>Description: Ensemble is Amdocs' platform that provides one of the leading customer care, billing and order management solutions for convergent telecom operations. It supports the full-range of fixed-line and mobile services.
</p><p>
Technologies: Cobol, Unix, SQL (Ya! I have worked on COBOL too :P)
</p>

<h3>Side projects using Ruby on Rails
</h3><p>Github profile: <a href="https://github.com/abhishekbose87/">https://github.com/abhishekbose87/</a>
</p><p class="project"><span class="headline">Pomarity</span> ( <a href="http://www.pomarity.in/">http://www.pomarity.in/</a> )
</p><p>       Created a website  to keep track of pomodoros completed every day. I used activeadmin gem to create an admin interface to enter data and javascript graphs to show the last week’s data. Hopefully one day this can be sponsored to help NGOs just like there are running events which act as fundraisers.
</p><p class="project"><span class="headline">execute-todo</span>(  <a href="http://execute-todo.herokuapp.com/">http://execute-todo.herokuapp.com/</a> )
</p><p>       Created a todo app where you can track the number of pomodoros worked on a particular task. It shows a notification when you have completed a pomodoro and brings focus to the window to decide whether the last pomodoro was valid or not.
</p><p class="project"><span class="headline">Personal website</span> ( <a href="http://abhishekbose.com/">http://abhishekbose.com/</a> )
</p><p>      Created a personal website for myself using ruby on rails.
</p><h3>Other fun projects:
</h3><p class="project"><span class="headline">OSCAR Brochure</span> ( <a href="http://goo.gl/ycj3D4">http://goo.gl/ycj3D4</a> )
</p><p>       Created a brochure for OSCAR India Organisation using Adobe Indesign
</p><p class="project"><span class="headline">Calendar for fundraising</span> ( <a href="http://goo.gl/kf7LPB">http://goo.gl/kf7LPB</a> )
</p><p>       Created a calendar using the photographs I had clicked in Ireland to raise funds for OSCAR India Organisation.
</p><p class="project"><span class="headline">Part time project with BBFS</span>
</p><p>      Currently working on a part time project with Bhaichung Bhutia Football Schools
</article>

app/views/static_pages/what_doing_now.html.erb
<% provide(:title, 'What am I doing now') %>
<article>
<h2>What am I doing right now ? </h2>
<p>I quit my job at Josh Software and now I am currently working from my hometown Jamshedpur. Been building a MVP for an idea related to photographers marketplace and also been freelancing on the side to make ends meet.
</p>
</article>
<div id="past-updates-section">
  <article>
    <h5> Feb 2014 </h5>
    <p>I am working in Josh software right now, one of the leading companies in India associated with Ruby on Rails. The learning curve is pretty steep but the environment is fun enough to get you through. It seems that I have got my programming mojo back which is a great thing and most importantly I have proved to myself that I can learn something new on my own and get employed in that domain.
    </p>
    <p>Happy for now .. and I am much more calmer :)</p>
  </article>
  <article>
    <h5>Aug 2013 </h5>
    <p>I am in the middle of a career break where I am trying to design a life which goes along with my definition of success.
    </p>
  </article>
</div>